version: '3.8'

services:
  # MongoDB
  mongodb:
    image: mongo:7.0
    container_name: llm_template_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-password}
      MONGO_INITDB_DATABASE: ${MONGODB_DB_NAME:-llm_template_db}
    volumes:
      - mongodb_data:/data/db
    networks:
      - llm_network

  # Redis for Celery
  redis:
    image: redis:7-alpine
    container_name: llm_template_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - llm_network

  # FastAPI Application
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: llm_template_app
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - MONGODB_URL=mongodb://${MONGO_USERNAME:-admin}:${MONGO_PASSWORD:-password}@mongodb:27017/${MONGODB_DB_NAME:-llm_template_db}?authSource=admin
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - ./app:/app/app
      - ./templates:/app/templates
      - ./tests:/app/tests
    depends_on:
      - mongodb
      - redis
    networks:
      - llm_network
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  # Celery Worker
  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: llm_template_celery
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - MONGODB_URL=mongodb://${MONGO_USERNAME:-admin}:${MONGO_PASSWORD:-password}@mongodb:27017/${MONGODB_DB_NAME:-llm_template_db}?authSource=admin
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - ./app:/app/app
    depends_on:
      - mongodb
      - redis
    networks:
      - llm_network
    command: celery -A app.celery_app worker --loglevel=info

  # Celery Beat (for scheduled tasks)
  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: llm_template_beat
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - MONGODB_URL=mongodb://${MONGO_USERNAME:-admin}:${MONGO_PASSWORD:-password}@mongodb:27017/${MONGODB_DB_NAME:-llm_template_db}?authSource=admin
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - ./app:/app/app
    depends_on:
      - mongodb
      - redis
    networks:
      - llm_network
    command: celery -A app.celery_app beat --loglevel=info

  # Flower (Celery monitoring)
  flower:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: llm_template_flower
    restart: unless-stopped
    ports:
      - "5555:5555"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
    networks:
      - llm_network
    command: celery -A app.celery_app flower --port=5555

  # Ollama (optional, for local LLM)
  ollama:
    image: ollama/ollama:latest
    container_name: llm_template_ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - llm_network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

networks:
  llm_network:
    driver: bridge

volumes:
  mongodb_data:
  ollama_data: